[package]
license = "MIT"
name = "webkit2gtk"
version = "0.1.0"

[dependencies]
bitflags = "^0.7"
gio = "^0.1.2"
gio-sys = "^0.3.3"
glib = "^0.1.2"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk = "^0.1.2"
gtk-sys = "^0.3.3"
libc = "^0.2"

[dependencies.javascriptcore]
git = "https://github.com/antoyo/javascriptcore-rs"
version = "0.1.0"

[dependencies.webkit2gtk-sys]
git = "https://github.com/antoyo/webkit2gtk-sys-rs"
branch = "crate"
version = "^0.3"

[features]
v2_10 = ["v2_8", "webkit2gtk-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-sys/v2_12"]
v2_2 = ["webkit2gtk-sys/v2_2"]
v2_4 = ["v2_2", "webkit2gtk-sys/v2_4"]
v2_6 = ["v2_4", "webkit2gtk-sys/v2_6"]
v2_8 = ["v2_6", "webkit2gtk-sys/v2_8"]
