[package]
license = "MIT"
name = "webkit2gtk"
version = "0.1.0"

[dependencies]
bitflags = "^0.9"
libc = "^0.2"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
version = "^0.1.3"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "^0.1.3"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "^0.1.3"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

# TODO: regenerate the crate (not working with latest gir).
[dependencies.javascriptcore]
git = "https://github.com/antoyo/javascriptcore-rs"
version = "0.1.0"

[dependencies.webkit2gtk-sys]
git = "https://github.com/antoyo/webkit2gtk-rs"
version = "^0.3"

[features]
v2_10 = ["v2_8", "webkit2gtk-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-sys/v2_12"]
v2_6 = ["webkit2gtk-sys/v2_6"]
v2_8 = ["v2_6", "webkit2gtk-sys/v2_8"]
