[package]
name = "webkit2gtk"
version = "0.3.0"
authors = ["The Gtk-rs Project Developers"]

categories = ["api-bindings", "gui"]
description = "Rust bindings for webkit-gtk library"
repository = "https://github.com/gtk-rs/webkit2gtk-rs"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/webkit2gtk"

keywords = ["webkit", "gtk-rs", "gnome", "GUI"]

[badges]
travis-ci = { repository = "gtk-rs/webkit2gtk-rs" }

[lib]
name = "webkit2gtk"

[features]
v2_2 = []
v2_4 = ["v2_2"]
v2_6 = ["v2_4", "webkit2gtk-sys/v2_6"]
v2_8 = ["v2_6", "webkit2gtk-sys/v2_8"]
v2_10 = ["v2_8", "webkit2gtk-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-sys/v2_12"]
v2_14 = ["v2_12", "webkit2gtk-sys/v2_14"]
v2_16 = ["v2_14", "webkit2gtk-sys/v2_16"]

[dependencies]
bitflags = "^1.0"
libc = "^0.2"
cairo-rs = "^0.3.0"
gdk = "^0.7.0"
gdk-sys = "^0.5.0"
gio = "^0.3.0"
gio-sys = "^0.5.0"
glib = "^0.4.0"
glib-sys = "^0.5.0"
gobject-sys = "^0.5.0"
gtk = "^0.3.0"
gtk-sys = "^0.5.0"
javascriptcore-rs = "^0.3.0"
webkit2gtk-sys = "^0.5"
