[package]
name = "webkit2gtk"
version = "0.5.0"
authors = ["The Gtk-rs Project Developers"]
categories = ["api-bindings", "gui"]
description = "Rust bindings for webkit-gtk library"
repository = "https://github.com/gtk-rs/webkit2gtk-rs"
license = "MIT"
homepage = "https://gtk-rs.org/"
documentation = "https://gtk-rs.github.io/webkit2gtk-rs/webkit2gtk"
keywords = ["webkit", "gtk-rs", "gnome", "GUI"]
exclude = [
    "gir-files/*",
]

[badges]
travis-ci = { repository = "gtk-rs/webkit2gtk-rs" }

[lib]
name = "webkit2gtk"

[features]
#default = ["v2_22"]
v2_2 = []
v2_4 = ["v2_2"]
v2_6 = ["v2_4", "webkit2gtk-sys/v2_6"]
v2_8 = ["v2_6", "webkit2gtk-sys/v2_8"]
v2_10 = ["v2_8", "webkit2gtk-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-sys/v2_12"]
v2_14 = ["v2_12", "webkit2gtk-sys/v2_14"]
v2_16 = ["v2_14", "webkit2gtk-sys/v2_16"]
v2_18 = ["v2_16", "webkit2gtk-sys/v2_18"]
v2_20 = ["v2_18", "webkit2gtk-sys/v2_20"]
v2_22 = ["v2_20", "webkit2gtk-sys/v2_22"]
v2_24 = ["v2_22", "webkit2gtk-sys/v2_24"]
v2_26 = ["v2_24", "webkit2gtk-sys/v2_26"]
v2_28 = ["v2_26", "webkit2gtk-sys/v2_28"]
v2_30 = ["v2_28", "webkit2gtk-sys/v2_30"]

[dependencies]
bitflags = "^1.0"
libc = "^0.2"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[dependencies.javascriptcore-rs]
git = "https://github.com/gtk-rs/javascriptcore-rs"

[dependencies.webkit2gtk-sys]
path = "./webkit2gtk-sys"
