[package]
name = "webkit2"
version = "0.1.0"
license = "MIT"

[dependencies]
bitflags = "^0.7"
libc = "^0.2"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
version = "0.1.0"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "0.1.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.javascriptcore]
git = "https://github.com/antoyo/javascriptcore-rs"
version = "0.1.0"

[dependencies.webkit2-sys]
git = "https://github.com/antoyo/webkit2-sys-rs"
version = "^0.3"
