[package]
name = "webkit2gtk"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]

categories = ["api-bindings", "gui"]
description = "Rust bindings for webkit-gtk library"
repository = "https://github.com/gtk-rs/webkit2gtk-rs"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/webkit2gtk"

keywords = ["webkit", "gtk-rs", "gnome", "GUI"]

[badges]
travis-ci = { repository = "gtk-rs/webkit2gtk-rs" }

[lib]
name = "webkit2gtk"

[features]
v2_2 = []
v2_4 = ["v2_2"]
v2_6 = ["v2_4", "webkit2gtk-sys/v2_6"]
v2_8 = ["v2_6", "webkit2gtk-sys/v2_8"]
v2_10 = ["v2_8", "webkit2gtk-sys/v2_10"]
v2_12 = ["v2_10", "webkit2gtk-sys/v2_12"]

[dependencies]
bitflags = "^0.9"
libc = "^0.2"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
version = "^0.1.3"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "^0.1.3"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "^0.1.3"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

# TODO: regenerate the crate (not working with latest gir).
[dependencies.javascriptcore]
git = "https://github.com/gtk-rs/javascriptcore-rs"
version = "0.1.0"

[dependencies.webkit2gtk-sys]
git = "https://github.com/guillaumegomez/webkit2gtk-rs"
version = "^0.3"
