[options]
gir_dir = "input"
library = "WebKit2"
version = "4.0"
work_mode = "normal"
generate_safety_asserts = true
external_libraries = [
    "Gio",
    "Gtk",
]

generate = [
    "WebKit2.AuthenticationRequest",
    "WebKit2.AuthenticationScheme",
    "WebKit2.BackForwardList",
    "WebKit2.BackForwardListItem",
    "WebKit2.CacheModel",
    "WebKit2.ColorChooserRequest",
    "WebKit2.ContextMenu",
    "WebKit2.ContextMenuAction",
    "WebKit2.ContextMenuItem",
    "WebKit2.CookieAcceptPolicy",
    "WebKit2.CookieManager",
    "WebKit2.CookiePersistentStorage",
    "WebKit2.CredentialPersistence",
    "WebKit2.Download",
    "WebKit2.DownloadError",
    "WebKit2.EditorState",
    "WebKit2.EditorTypingAttributes",
    "WebKit2.Error",
    "WebKit2.FaviconDatabase",
    "WebKit2.FaviconDatabaseError",
    "WebKit2.FindController",
    "WebKit2.FindOptions",
    "WebKit2.FormSubmissionRequest",
    "WebKit2.GeolocationPermissionRequest",
    "WebKit2.HitTestResult",
    "WebKit2.HitTestResultContext",
    "WebKit2.InsecureContentEvent",
    "WebKit2.InstallMissingMediaPluginsPermissionRequest",
    "WebKit2.JavascriptError",
    "WebKit2.JavascriptResult",
    "WebKit2.LoadEvent",
    "WebKit2.NavigationAction",
    "WebKit2.NavigationPolicyDecision",
    "WebKit2.NavigationType",
    "WebKit2.NetworkError",
    "WebKit2.Notification",
    "WebKit2.NotificationPermissionRequest",
    "WebKit2.PermissionRequest",
    "WebKit2.Plugin",
    "WebKit2.PluginError",
    "WebKit2.PolicyDecision",
    "WebKit2.PolicyDecisionType",
    "WebKit2.PolicyError",
    "WebKit2.ProcessModel",
    "WebKit2.PrintError",
    "WebKit2.PrintOperation",
    "WebKit2.PrintOperationResponse",
    "WebKit2.ResponsePolicyDecision",
    "WebKit2.SaveMode",
    "WebKit2.ScriptDialogType",
    "WebKit2.SecurityManager",
    "WebKit2.Settings",
    "WebKit2.SnapshotError",
    "WebKit2.SnapshotOptions",
    "WebKit2.SnapshotRegion",
    "WebKit2.TLSErrorsPolicy",
    "WebKit2.UserContentInjectedFrames",
    "WebKit2.UserMediaPermissionRequest",
    "WebKit2.UserScriptInjectionTime",
    "WebKit2.UserStyleLevel",
    "WebKit2.Version",
    "WebKit2.WebContext",
    "WebKit2.WebInspector",
    "WebKit2.WebResource",
    "WebKit2.WebsiteDataManager",
    "WebKit2.WindowProperties",
]

manual = [
    "Gio.AsyncResult",
    "Gio.Cancellable",
    "Glib.Error",
    "GObject.Object",
    "Gtk.Container",
    "Gtk.Widget",
]

[[object]]
name = "WebKit2.URISchemeRequest"
status = "generate"
module_name = "uri_scheme_request"

[[object]]
name = "WebKit2.URIRequest"
status = "generate"
module_name = "uri_request"

[[object]]
name = "WebKit2.URIResponse"
status = "generate"
module_name = "uri_response"

[[object]]
name = "WebKit2.WebView"
status = "generate"
    [[object.signal]]
    name = "create"
    version = "2.6"
