[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
atk-sys = "^0.3.3"
bitflags = "0.9"
cairo-sys-rs = "^0.3.3"
gdk-pixbuf-sys = "^0.3.3"
gdk-sys = "^0.3.3"
gio-sys = "^0.3.3"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk-sys = "^0.3.3"
libc = "0.2"
pango-sys = "^0.3.3"

# TODO: switch to the version published on crates.io.
[dependencies.javascriptcore-sys]
git = "https://github.com/antoyo/javascriptcore-sys-rs"
version = "0.1.0"

# TODO: switch to the version published on crates.io.
[dependencies.soup-sys]
branch = "crate"
git = "https://github.com/antoyo/soup-sys-rs"
version = "^0.3"

[features]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_6 = []
v2_8 = ["v2_6"]

[lib]
name = "webkit2gtk_sys"

[package]
build = "build.rs"
license = "MIT"
links = "web_kit2"
name = "webkit2gtk-sys"
version = "0.3.1"
