[badges.travis-ci]
repository = "gtk-rs/webkit2gtk-rs"

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
atk-sys = "^0.7.0"
bitflags = "1.0"
cairo-sys-rs = "^0.7.0"
gdk-pixbuf-sys = "^0.7.0"
gdk-sys = "^0.7.0"
gio-sys = "^0.7.0"
glib-sys = "^0.7.0"
gobject-sys = "^0.7.0"
gtk-sys = "^0.7.0"
javascriptcore-rs-sys = "^0.1.0"
libc = "0.2"
pango-sys = "^0.7.0"
soup-sys = "^0.7.0"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]
v2_18 = ["v2_16"]
v2_20 = ["v2_18"]
v2_6 = []
v2_8 = ["v2_6"]

[lib]
name = "webkit2gtk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
categories = ["api-bindings", "gui"]
description = "Rust binding for webkit-gtk library"
homepage = "http://gtk-rs.org"
keywords = ["webkit", "gtk-rs", "gnome", "GUI"]
license = "MIT"
links = "web_kit2"
name = "webkit2gtk-sys"
repository = "https://github.com/gtk-rs/webkit2gtk-rs"
version = "0.7.0"
