[package]
build = "build.rs"
license = "MIT"
links = "web_kit2"
name = "webkit2gtk-sys"
version = "0.3.1"

[lib]
name = "webkit2gtk_sys"

[features]
v2_6 = []
v2_8 = ["v2_6"]
v2_10 = ["v2_8"]
v2_12 = ["v2_10"]
v2_14 = ["v2_12"]
v2_16 = ["v2_14"]

[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.9"
libc = "0.2"

[dependencies.atk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "^0.3.4"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.javascriptcore-sys]
git = "https://github.com/gtk-rs/javascriptcore-rs"
version = "0.1.0"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "^0.3.4"

[dependencies.soup-sys]
git = "https://github.com/gtk-rs/soup-sys-rs"
version = "^0.3"
